name: Let Her Cook — Pulse Tracker

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install requests

      - name: Run pulse tracker
        env:
          LHC_TOKEN: ${{ secrets.LHC_TOKEN }}
          LHC_USERNAME: ${{ secrets.LHC_USERNAME }}
        run: python tracker/logic/pulse_tracker.py

      - name: Commit update
        run: |
          git config --global user.name "lhc-bot"
          git config --global user.email "lhc@users.noreply.github.com"
          git add cook-log.json
          git commit -m "🔁 EldrPulse update"

                - name: Commit update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "lhc-bot"
          git config --global user.email "lhc@users.noreply.github.com"
          git add cook-log.json
          git commit -m "🔁 EldrPulse update" || echo "Nothing to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main

