name: Let Her Cook — Pulse Tracker

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  pulse:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed for pushing to the repository
    steps:
      - name: Set up job
        run: echo "Starting pulse tracker job"
      
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for more accurate stats
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any required dependencies here
          # pip install -r requirements.txt
      
      - name: Run pulse tracker
        run: |
          # Use python -m to run the module properly
          python -m tracker.logic.pulse_tracker
      
      - name: Commit pulse log update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cook-log.json
          git commit -m "Update pulse log [automated]" || echo "No changes to commit"
          git push